DROP DATABASE IF EXIST centro_computo;
CREATE DATABASE centro_computo CHARACTER SET utf8mb4;
USE centro_computo;

CREATE TABLE incidente (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	nombre VARCHAR(120) NOT NULL,
	correo VARCHAR(120) NOT NULL,
	rol VARCHAR(50) NOT NULL,
	tipo VARCHAR(80) NOT NULL,
	descripcion TEXT NOT NULL,
	evidencia VARCHAR(255) DEFAULT NULL,
	fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
