#+title: Notas Criptografia - Semestre VI

* Introdución
- Profesor: Hector Xavier Limón Riaño
- Materia: Criptografia
- Contacto: xavier120@hotmail.com
- Carrera: Ciberseguridad e Infraestructura de Computo

* Información
** Prerrequisitos:
  - Estructuras de datos (Python)
  - Matematicas para la ciberseguridad
  - Ciberseguridad
  - Manipulacion de archivos de texto y binarios
  - Manipulacion de cadenas de texto y binarios
  - Manipulacion de datos binarios
  - Sockets TCP
** Evaluación:
- Examenes: 60%
- Tareas y practicas: 20%
- Proyecto: 20%
** Herramientas:
- Eminus
- Entorno controlado para examenes
- Practical Cryptography in Python - Libro de Referencia

* Temario
** Descripción
Es un elemento fundamental de la protección de la información.

** Unidad 1
- Cifrado Cesar
- Usos de la criptografia
- Criptografia y criptoanalisis

** Unidad 2
- Funciones de hash
- AES
- Modos de operación de AES
- Padding
- Manejo de llaves y vectores de inicialización

** Unidad 3
- Llaves publicas y privadas
- RSA
- PKCS

** Unidad 4
- MAC, HMAC. CBC-MAC
- Firmas digitales
- Curvas

* Introducción a la criptografia
- CIA:
  Confidencialidad -> Impide ver algo a quien no debe verlo.
  Integridad -> Evitar la manipulación de los datos.
  Disponibilidad -> Tener la posibilidad de acceder a los datos (que tengamos permiso) en cualquier momento.

Autenticar -> Probar que eres quien dices ser.
Autorizar -> Dar acceso al que se autentica mediante permisos.

Secretos

Llaves privadas

Datos pueden estar en 3 estados:
- Reposo -> Esta almacenado en disco.
- Transito -> Estan viajando por la red.
- Uso -> Estan en la memoria

** STRIDE
- Spoofing: Suplantar la identidad en redes informaticas haciendose pasar por una persona, entidad o sistema de confianza para engañar a la victima. Se puede mitigar por firmas digitales, contraseñas, etc.
- Tampering: Alterar, manipular o interferir con algo sin autorización, generalmente con el fin de causar daño, obtener beneficios ilegales o comprometer la integridad de un sistema, proceso o evidencia. Usa la tecnologia de hash para mitigarlo.
- Repudation: El acto de negar, por parte de una persona o sistema, haber realizado una acción, transacción o comunicación especifica.
- Information disclosure: Acceso no autorizado o la revelación inadvertida de datos sensibles, confidenciales o privados a personas, sistemas o entidades que no deberian tener acceso a ellos.
- Denegation of service: Hacer que un sistema, servicio o red sea inaccesible para sus usuarios legitimos.
- Elevation of privileges: Otorgar permisos a usuarios que no deben de tener dichos permisos.

** Origen de la criptografia
- Viene del griego kryptos que significa oculto y graphe que signfica grafo o escritura.
- Es un ambito de la criptologia que se ocupa de las tecnicas de cifrado o codificado destinadas a alterar las representaciones linguisticas de cierntos mensajes con el fin de hacerlos ininteligibles.
- Se encarga del estudio de los algoritmos, protocolos criptograficos, y sistemas que se utilizan para proteger la información y dotar de seguridad a las comunicaciones y a las entidades que se comunican.
- El criptoanalisis es la parte que se dedica al estudio de los sistema criptograficos con el fin de encontrar debilidades en los sistemas y romper su seguridad sin el conocimiento de información secreta.

** Criptografia
- Esta en todos lados: ssh, criptomonedas y cualquier aplicación web.
- Es un pilar de la seguridad informatica moderna.
- La criptografia no es solo cifrado, se utiliza tambien para autenticación e integridad de los datos.
- La criptografia bien implementada es efectiva sin importar:
  - Que tan bien educado este el adversario.
  - Que tantas computadoras tenga el adversario.
  - Si el adversario conoce los algoritmos usados.
  - Que tan motivado este el adversario.
- La efectivad de la criptografia depende usualmente del contexto.
- La buena seguridad depende de siempre kde tus elecciones.
- Se debe de tomar la decisión adecuada de acuerdo al contexto del problema.
- Nunca utilices un metodo criptografico si no entiendes su contexto de uso y su correcta configuración.
- Nunca utilices un metodo criptografico usando la configuración por defecto a menos que la conozcas.
- Revisa bien los metodos criptograficos que aplicaras muchos tienen vulnerabilidades conocidas.
- TLS: Transport Layer Security, es la base para otras tecnologias como HTTPS y VPN.
- OpenSSL
- Determinismo -> Es predecible

*** Tres protecciones principales de la criptografia
- Autenticidad: Firmas digitales, Codigos MAC.
- Confidencialidad: Cifrado, intercambio de llaves.
- Integridad: Hashing.

*** AES
- Estandar de cifrado asimetrico.

*** YANAC
- YANAC: You Are Not A Criptographer. Acronimo popular en la comunidad criptografica.
- Dont roll your own crypto.
- Es mas facil usar mal los metodos criptograficos que usarlos bien.
- Abstente de crear tus propios metodos criptograficos.
- Hasta expertos criptograficos han creado metodos con vulnerabilidades.
- Un nuevo metodo pasa por muchas revisiones de expertos antes de ser usado de forma practica.
- Incluso debes de abstenerte de hacer tus propias

*** Codificar
- Transformar de una representacion a otra sin perdida.
- Base64

*** Cifrar
- Es el proceso de convertir informacion sensible en un formato ilegible mediante un secreto (llave) a las que solo partes autorizadas tienen acceso.

*** Ofuscar
- Se refiere a encubrir el significado haciendola mas confusa y complicada de interpretar.

*** Hashear
- Es la funcion de aplicar una funcion de hash, es decir, que transforma un conjunto de datos en una cadena alfanumerica unica que actua como una huella digital del contenido original. No es invertible.

*** Cifrado cesar
- Se basaen reemplazar una letra de un mensaje por otra letra.
- Se puede aplicar tanto a texto como a binario.
- Si es binario debe considerarse el modulo 256, si es texto debe cuidarse el valor ASCII

*** Aritmetica Modular
- 4 % 4
- (144 + 300) % 256 = 188
- (188 - 300) % 256 = 144
- El resultado sera siempre un numero natural.
-

*** Binario
- El binario se manipula en paquetes de bytes (8 bits), no se puede manipular directamentes menos (al menos en las arquitecturas populares modernas).

- Tarea: Cifrado cesar para archivo de texto.

** Hashing
- 3**2 = 9 -> Biyectivas
- 22 % 2 = 0 ->

- El hashing es uno de los elementos principales de la seguridad criptografia.
- Algunas funciones de hash son mejores que otras cumpliendo las propiedades antes mencionadas.
- Buenas: SHA-256, SHA-512
- No tan buenas: MD5, SHA-1. Estas no deberian ser usadas por sus vectores de seguridad.
- Solo funciona con cadenas binarias

*** Cifrado vs Hashing
- El cifrado permite tener confidencialidad en los mensajes, pero ayuda a verificar la interidad de los mismos.
- Confidencialidad: Solo las personas autorizadas pueden leer el mensaje.
- Integridad: Las personas no autorizadas no pueden cambiar el contenido del mensaje sin que dicho cambio pueda ser percibido.
- Solo porque un mensaje este cifrado (no pueda ser leido) no significa que no pueda ser alterado, incluso de formas que tengan sentido despues de cifrar.

**** DIGESTS
- Su traduccion seria "resumen"
- Una funcion de hash produce un resumen o huella digital de algun contenido binario
- Este resumen puede utilizarse como medida para verificacion de tampering (alteraciones de informacion), utilizadas en analisis forense.
- En una transmision la idea es transmitir el mensaje junto con su digest, para verificar que haya llegado sin alteraciones.

***** hashlib
import hashlib
md5hasher = hashlib.md5(b'cadenaBin')
md5hasher.hexdigest()
md5hasher.update(b'continuacionCadenaBin')
md5hasher.hexdigest()

*** Funciones de hash
- Una funcion de hash toma un contenido de cualquier tamano(hasta vacio) y siempre produce un numero de un tamano fijo.
- Por ejemplo, MD5 produce una salida de 16 bytes
- Este tamano tiene una relacion con la seguridad de la funcion entre mas pequenos es peor.
- Dominio -> Codominio
- Una vez mas, las propiedades que una funcion de hash debe de cumplir son:
  - El mismo documento siempre produce el mismo digest.
  - El digest parece aleatorio, si tienes el digest eso no te da pistas del documento de entrada.
  - Idealmente cada documento con contenido diferente deberia tener un digest diferente (lo cual en realidad no es posible).

- Los digests son como huellas digitales: si tienes al sujeto se puede verificar que sea quien dice ser mediante su huella digital.
- Sin embargo, si solo tiene la huella digital no es facil determinar el sujeto que la posee.
- Es facil calcular el digests de un documento, pero si tiene solo el digest es muy dificil determinar el documento que lo produjo, entre mas dificil mejor.
- Por esta razon son llamadas funciones de una sola via, se puede ir de entrada a la salida pero no al revez.

**** Ejercicio

- Extiende el cifrador ce Cesar binario para que incluya una verificacion de integridad mediante SHA-256
- El profesor demostrara como agregar el hash en el cifrado
- Tu tarea consistira en verificar el hash al descifrar, lanzando una excepcion si el archivo cifrado es alterado.

*** Hashing
- En computacion, el termino funcion de hash casi siempre se refiere a una funcion criptografica.
- Sin embargo, el termino general
- El tamano del codominio depende de la funcion de hash, por ejemplo, ya se dijo que MD5 genera digest de 16 bytes. Cual es el tamano del codominio para MD5?
- SI se considera un numero muy grande de documentos de entrada es posible que muchos de ellos produzcan el mismo hash.
- Dado lo anterior, las funciones de hash tienen perdida. Se pierde informacion de la fuente al digest.
- Que tenga perdida es importante, de lo contrario habria una forma de regresar del digest al documento original.
- Considerando de nuevo la funcion par
- Cualquier numero puede dar como resultado 0 (par) o 1 (inpar)
- Seria posible saber, dado un valor 0 o 1que numero produjo dicho resultado
- Esta funcion tiene todas las propiedades: tienen perdida, comprime la entrada,
- Las propiedades de consistencia, compresion y perdida son comunes en cualquier funcion de hash pero no suficientes para ser seguras o criptograficas.
- Se requieren las sig. propiedades:
  - Resistencia de preimagen.
  - Segunda resistencia de preimagen.
  - Resistencia de colisiones.

**** Resistencia de preimagen
- Es el conjunto de entradas de una funcion de hash que producen
- Una preimagen de una funcion de hash H y un valor de hash k es el conjunto de valores x por el cual H(x) = k
- Al tener un digest, existe un numero infinito de documentos que produjeron dicho digest.
- Eso no quiere decir que dado un digest sea facil encontrar un elemento de la preimagen
- La resistencia de preimagen es basicamente: si tengo un digest y no se como se obtuvo, no pudo ni siquiera encontrar un elemento en la preimagen sin realizar una cantidad ridicula de trabajo computacional.
- Intratable -> Se puede resolver, pero cuesta demasiado
- No computable -> No se puede resolver con una computadora
- Idealmente, los elementos de la preimagen deberian estar muy separados entre ellos y no tener un espaciado predecible
- El hecho de que las funciones de hash tengan perdida ayuda a la resistencia de preimagen
- Si una funcion de hash tiene buena resistencia de preimagen, los ataques en este sentido seran aleatorios o bien consistiran en enumeraciones muy largas (fuerza bruta) hasta encontrar una coincidencia, lo cual no es computacionalmente tratable.
- Al proceso de intentar encontrar un elemento de la preimagen dado un valor de hash se le llama invertir el hash
- Encontrar un inverso

**** Segunda resistencia de preimagen
- Si tu tienes al menos un documento que produce un hash conocido, sigue siendo muy dificil encontrar otro documento que produzca el mismo hash
-
