#+title: Notas Criptografia - Semestre VI

* Introdución
- Profesor: Hector Xavier Limón Riaño
- Materia: Criptografia
- Contacto: xavier120@hotmail.com
- Carrera: Ciberseguridad e Infraestructura de Computo

* Información
** Prerrequisitos:
  - Estructuras de datos (Python)
  - Matematicas para la ciberseguridad
  - Ciberseguridad
  - Manipulacion de archivos de texto y binarios
  - Manipulacion de cadenas de texto y binarios
  - Manipulacion de datos binarios
  - Sockets TCP
** Evaluación:
- Examenes: 60%
- Tareas y practicas: 20%
- Proyecto: 20%
** Herramientas:
- Eminus
- Entorno controlado para examenes
- Practical Cryptography in Python - Libro de Referencia

* Temario
** Descripción
Es un elemento fundamental de la protección de la información.

** Unidad 1
- Cifrado Cesar
- Usos de la criptografia
- Criptografia y criptoanalisis

** Unidad 2
- Funciones de hash
- AES
- Modos de operación de AES
- Padding
- Manejo de llaves y vectores de inicialización

** Unidad 3
- Llaves publicas y privadas
- RSA
- PKCS

** Unidad 4
- MAC, HMAC. CBC-MAC
- Firmas digitales
- Curvas

* Introducción a la criptografia
- CIA:
  Confidencialidad -> Impide ver algo a quien no debe verlo.
  Integridad -> Evitar la manipulación de los datos.
  Disponibilidad -> Tener la posibilidad de acceder a los datos (que tengamos permiso) en cualquier momento.

Autenticar -> Probar que eres quien dices ser.
Autorizar -> Dar acceso al que se autentica mediante permisos.

Secretos

Llaves privadas

Datos pueden estar en 3 estados:
- Reposo -> Esta almacenado en disco.
- Transito -> Estan viajando por la red.
- Uso -> Estan en la memoria

** STRIDE
- STRIDE es un modelo de amenazas, utilizado para ayudar a razonar y encontrar amenazas a un sistema.

- Spoofing: Suplantar la identidad en redes informaticas haciendose pasar por una persona, entidad o sistema de confianza para engañar a la victima. Se puede mitigar por firmas digitales, contraseñas, etc. -> Autenticidad

- Tampering: Alterar, manipular o interferir con algo sin autorización, generalmente con el fin de causar daño, obtener beneficios ilegales o comprometer la integridad de un sistema, proceso o evidencia. Usa la tecnologia de hash para mitigarlo. -> Integridad

- Repudation: El acto de negar, por parte de una persona o sistema, haber realizado una acción, transacción o comunicación especifica. -> No repudio

- Information disclosure: Acceso no autorizado o la revelación inadvertida de datos sensibles, confidenciales o privados a personas, sistemas o entidades que no deberian tener acceso a ellos. -> Confidencialidad

- Denegation of service: Hacer que un sistema, servicio o red sea inaccesible para sus usuarios legitimos. -> Disponibilidad

- Elevation of privileges: Otorgar permisos a usuarios que no deben de tener dichos permisos. -> Autorizacion

** Origen de la criptografia
- Viene del griego kryptos que significa oculto y graphe que signfica grafo o escritura.
- Es un ambito de la criptologia que se ocupa de las tecnicas de cifrado o codificado destinadas a alterar las representaciones linguisticas de cierntos mensajes con el fin de hacerlos ininteligibles.
- Se encarga del estudio de los algoritmos, protocolos criptograficos, y sistemas que se utilizan para proteger la información y dotar de seguridad a las comunicaciones y a las entidades que se comunican.
- El criptoanalisis es la parte que se dedica al estudio de los sistema criptograficos con el fin de encontrar debilidades en los sistemas y romper su seguridad sin el conocimiento de información secreta.

** Criptografia
- Esta en todos lados: ssh, criptomonedas y cualquier aplicación web.
- Es un pilar de la seguridad informatica moderna.
- La criptografia no es solo cifrado, se utiliza tambien para autenticación e integridad de los datos.
- La criptografia bien implementada es efectiva sin importar:
  - Que tan bien educado este el adversario.
  - Que tantas computadoras tenga el adversario.
  - Si el adversario conoce los algoritmos usados.
  - Que tan motivado este el adversario.
- La efectivad de la criptografia depende usualmente del contexto.
- La buena seguridad depende de siempre kde tus elecciones.
- Se debe de tomar la decisión adecuada de acuerdo al contexto del problema.
  - Nunca utilices un metodo criptografico si no entiendes su contexto de uso y su correcta configuración.
  - Nunca utilices un metodo criptografico usando la configuración por defecto a menos que la conozcas.
- Revisa bien los metodos criptograficos que aplicaras muchos tienen vulnerabilidades conocidas.
- TLS: Transport Layer Security, es la base para otras tecnologias como HTTPS y VPN.
- OpenSSL
- Determinismo -> Es predecible

*** Herramientas
- cryptography: Biblioteca de python con todos los algoritmos criptograficos que se usaran en el curso.
- gmpy2: Biblioteca python para el tratamiento matematico de numeros grandes.

*** Cifrado Cesar
- Consiste en reemplazar una letra de un mensaje por otra letra, o tambien, desplazar por un valor x (shift-cipher) el numero de letras.
  - Se puede aplica tanto a texto como a binario.
    - Si es binario debe considerarse el modulo 256
    - Si es texto debe considerarse el valor ASCII

*** Tres protecciones principales de la criptografia
- Autenticidad: Firmas digitales, Codigos MAC.
- Confidencialidad: Cifrado, intercambio de llaves.
- Integridad: Hashing.

*** AES
- Estandar de cifrado asimetrico.
- Advanced Encryption Standard.
- Es el algoritmo de cifrado simetrico mas usado en la actualidad.
- Lo utiliza TLS (HTTPS) y las funciones de cifrado de sistemas de archivos de un OS.
- Debe de saberse utilizar, tiene diferentes modos de operacion, algunos de ellos inseguros.
- Existen variantes, como AES-128 que utiliza una llave de 16 bytes.
- Una llave con contenido aleatorio es una llave valida.

*** YANAC
- YANAC: You Are Not A Criptographer. Acronimo popular en la comunidad criptografica.
- Dont roll your own crypto.
- Es mas facil usar mal los metodos criptograficos que usarlos bien.
- Abstente de crear tus propios metodos criptograficos.
- Hasta expertos criptograficos han creado metodos con vulnerabilidades.
- Un nuevo metodo pasa por muchas revisiones de expertos antes de ser usado de forma practica.
- Incluso debes de abstenerte de hacer tus propias

*** Codificar
- Transformar de una representacion a otra sin perdida.
- Base64

*** Cifrar
- Es el proceso de convertir informacion sensible en un formato ilegible mediante un secreto (llave) a las que solo partes autorizadas tienen acceso.

*** Ofuscar
- Se refiere a encubrir el significado haciendola mas confusa y complicada de interpretar.

*** Hashear
- Es la funcion de aplicar una funcion de hash, es decir, que transforma un conjunto de datos en una cadena alfanumerica unica que actua como una huella digital del contenido original. No es invertible.

*** Cifrado cesar
- Se basaen reemplazar una letra de un mensaje por otra letra.
- Se puede aplicar tanto a texto como a binario.
- Si es binario debe considerarse el modulo 256, si es texto debe cuidarse el valor ASCII

*** Aritmetica Modular
- 4 % 4
- (144 + 300) % 256 = 188
- (188 - 300) % 256 = 144
- El resultado sera siempre un numero natural.

*** Binario
- El binario se manipula en paquetes de bytes (8 bits), no se puede manipular directamentes menos (al menos en las arquitecturas populares modernas).

- Tarea: Cifrado cesar para archivo de texto.

** Hashing
- 3**2 = 9 -> Biyectivas
- 22 % 2 = 0 ->

- El hashing es uno de los elementos principales de la seguridad criptografia. Involucra el concepto de una funcion de una sola via y huella digital.
  - Una funcion hash solo funciona si cumple con los siguientes requisitos:
    1. Producen valores unicos y repetibles, es decir, son deterministas para cada entrada.
    2. El valor de salida no da ninguna pista (o patron) con respecto a la entrada que lo produjo.

- Algunas funciones de hash son mejores que otras cumpliendo las propiedades antes mencionadas.
- Buenas: SHA-256, SHA-512
- No tan buenas: MD5, SHA-1. Estas no deberian ser usadas por sus vectores de seguridad.
- Solo funciona con cadenas binarias

*** Cifrado vs Hashing
- El cifrado permite tener confidencialidad en los mensajes, pero ayuda a verificar la interidad de los mismos.
- Confidencialidad: Solo las personas autorizadas pueden leer el mensaje.
- Integridad: Las personas no autorizadas no pueden cambiar el contenido del mensaje sin que dicho cambio pueda ser percibido.
- Solo porque un mensaje este cifrado (no pueda ser leido) no significa que no pueda ser alterado, incluso de formas que no tengan sentido despues de cifrar.

*** DIGESTS
- Su traduccion seria "resumen"
- Una funcion de hash produce un resumen o huella digital de algun contenido binario
- Este resumen puede utilizarse como medida para verificacion de tampering (alteraciones de informacion), utilizadas en analisis forense.
- En una transmision la idea es transmitir el mensaje junto con su digest, para verificar que haya llegado sin alteraciones.

*** hashlib
import hashlib
md5hasher = hashlib.md5(b'cadenaBin')
md5hasher.hexdigest()
md5hasher.update(b'continuacionCadenaBin')
md5hasher.hexdigest()

*** Funciones de hash
- Una funcion de hash toma un contenido de cualquier tamano(hasta vacio) y siempre produce un numero de un tamano fijo.
- Por ejemplo, MD5 produce una salida de 16 bytes
- Este tamano tiene una relacion con la seguridad de la funcion entre mas pequenos es peor.
- Dominio -> Codominio
- Una vez mas, las propiedades que una funcion de hash debe de cumplir son:
  - El mismo documento siempre produce el mismo digest.
  - El digest parece aleatorio, si tienes el digest eso no te da pistas del documento de entrada.
  - Idealmente cada documento con contenido diferente deberia tener un digest diferente (lo cual en realidad no es posible).

- Los digests son como huellas digitales: si tienes al sujeto se puede verificar que sea quien dice ser mediante su huella digital.
- Sin embargo, si solo tiene la huella digital no es facil determinar el sujeto que la posee.
- Es facil calcular el digests de un documento, pero si tiene solo el digest es muy dificil determinar el documento que lo produjo, entre mas dificil mejor.
- Por esta razon son llamadas funciones de una sola via, se puede ir de entrada a la salida pero no al reves.

*** Hashing
- En computacion, el termino funcion de hash casi siempre se refiere a una funcion criptografica.
- Sin embargo, el termino es general
- Por ejemplo: Una funcion hash que establece si un numero es par o impar. Esencialmente, las funciones hash relaciona elementos de un dominio muy grande, con elementos de un codominio relativamente pequeno.
- El tamano del codominio depende de la funcion de hash, por ejemplo, ya se dijo que MD5 genera digest de 16 bytes. Cual es el tamano del codominio para MD5?
- SI se considera un numero muy grande de documentos de entrada es posible que muchos de ellos produzcan el mismo hash.
- Dado lo anterior, las funciones de hash tienen perdida. Se pierde informacion de la fuente al digest.
- Que tenga perdida es importante, de lo contrario habria una forma de regresar del digest al documento original.
- Considerando de nuevo la funcion par
- Cualquier numero puede dar como resultado 0 (par) o 1 (inpar)
- Seria posible saber, dado un valor 0 o 1que numero produjo dicho resultado
- Esta funcion tiene todas las propiedades: tienen perdida, comprime la entrada y es consistente ya que dada la misma entrada siempre produce la misma salida.

- Las propiedades de consistencia, compresion y perdida son comunes en cualquier funcion de hash pero no suficientes para ser seguras o criptograficas.
- Se requieren las sig. propiedades:
  - Resistencia de preimagen.
  - Segunda resistencia de preimagen.
  - Resistencia de colisiones.

**** Resistencia de preimagen
- Una preimagen es el conjunto de entradas de una funcion de hash que producen, en el caso de par o impar, una preimagen son todos los numeros pares que den valor 0.
- Una preimagen de una funcion de hash H y un valor de hash k es el conjunto de valores x por el cual H(x) = k

- Al tener un digest, existe un numero infinito de documentos que produjeron dicho digest.
- Eso no quiere decir que dado un digest sea facil encontrar un elemento de la preimagen

- La resistencia de preimagen es basicamente: si tengo un digest y no se como se obtuvo, no pudo ni siquiera encontrar un elemento en la preimagen sin realizar una cantidad ridicula de trabajo computacional.

- Intratable -> Se puede resolver, pero cuesta demasiado
- No computable -> No se puede resolver con una computadora
- Idealmente, los elementos de la preimagen deberian estar muy separados entre ellos y no tener un espaciado predecible
- El hecho de que las funciones de hash tengan perdida ayuda a la resistencia de preimagen
- Si una funcion de hash tiene buena resistencia de preimagen, los ataques en este sentido seran aleatorios o bien consistiran en enumeraciones muy largas (fuerza bruta) hasta encontrar una coincidencia, lo cual no es computacionalmente tratable.
- Al proceso de intentar encontrar un elemento de la preimagen dado un valor de hash se le llama invertir el hash
- Encontrar un inverso deberia ser muy dificil.

**** Segunda resistencia de preimagen
- Si tu tienes al menos un documento que produce un hash conocido, sigue siendo muy dificil encontrar otro documento que produzca el mismo hash.
- Esto funciona porque no existe patron repetible en los elementos de la preimagen.

**** Resistencia a colisiones
- Significa que es dificil encontrar dos entradas que produzcan el mismo hash y garantiza que sea computacionalmente inviable encontrar dos entradas diferentes que produzcan el mismo valor hash.
- No un hash especifico sino cualquier hash.
- Es mas facil encontrar una colision en un hash cualquiera que encontrar un elemento de la preimagen de un hash dado.
- Propiedad avalancha: El valor de hash cambia drasticamente y de forma impredecible, un minimo del 50% de los bits del hash deberia ser diferente.

*** Seguridad en funciones de hash
- Hash es usado para el almacenamiento de passwords, pero siguen teniendo problemas de seguridad, el mas comun es la situacion donde dos usuarios usen la misma contrasena y por tanto, genere el mismo hash, existen muchas soluciones (A2F, Token fisico, etc) pero la mas recomendada es agregqar un salt.

  - Salt: Es un valor usualmente aleatorio que se debe de agregar al password antes de aplicarse a la funcion de hash. Debido a la propiedad de avalancha, con el salt el hash resultante cambiara drasticamente. Y como son aleatorios, es poco probable que dos usuarios con la misma password tenga el mismo salt.

salt = os.urandom(16)

** Cifrado simetrico
- Cifrado que usa la misma llave para cifrar y descifrar, la llave es un secreto compartido.

*** AES
- Advanced Encryption Standard
- Lo utiliza TLS (HTTPS) y funciones de cifrado de sistemas de archivos de un OS.
- AES es un cifrador de bloque, cifra por bloques de 16 bytes, si no cumple con los 16 bytes se debe de agregar un padding (datos de relleno).
- Tambien puede cifrar un byte a la vez, esto se concoe como cifrado de flujo y no necesitan padding.
- En general, es mas eficiente cifrar bloques que en flujo.

**** Modos de operacion de AES
***** ECB - Electronic Code Book
- Cualquier texto plano de 16 bytes tiene 16 bytes correspondientes de salida.
- Cada bloque es tratado independientemente, esa es su debilidad.
  - Puede generar un ataque de texto plano escogido, que se basa en tener muchos mensajes de estructura parecida para enganar con un mensaje falso con una respuesta predecible.
- Parametros: Texto plano y llave.

***** CBC - Cipher Block Chaining
- Despues de cifrar el bloque aplicar una funcion XOR con el siguiente bloque en texto plano, el resultado se cifra y se guarda ese bloque. Para descifrar se tiene que invertir el proceso.
- Para el primer bloque a cifrar, se utiliza el IV dado que no hay un bloque anterior para hacer XOR, el IV debe de ser del mismo tamano del bloque (16 bytes).
  - Parametros: Texto plano, llave e IV
  - Debe de tener su respectivo padding.

***** CTR - Counter Mode
- No requiere de padding
- Genera un key stream de cualquier longitud a partir de una llave AES de al menos 128 bits (16 bytes), luego aplica XOR para combinarlos.
- CTR incrementa el contador en uno y asi sucesivamente. Si el texto plano no es multiplo de 16, los ultimos 16 bytes del key stream se truncan para corresponder al texto.
- Al IV se le llama nonce.
- CTR puede cifrar de forma independiente.
- Parametros: key, nonce, texto plano.

*** Seguridad en cifrado simetrico
- Para tener un cifrado seguro y efectivo se necesita:
  1. Cifrar el mismo mensaje de forma diferente cada vez que se haga, aunque se use la misma
     llave.
  2. Eliminar patrones predecibles entre los bloques. (Maleabilidad entre bloques)

- Para resolver el primer problema, se utiliza un vector de inicializacion (IV), el cual es una cadena aleatoria externa al texto plano y la llave. El IV es publico ya que solo hace que los mensajes no sean repetibles y no generar patrones.
- Nunca debe reusarse el mismo IV
- Existen ataques donde si conoces el texto plano y el IV (suponiendo que lo reutilizan) puedes obtener el key-stream.

** Cifrado asimetrico
- Las tecnicas asimetricas son variadas, no se limitan solo a cifrado
  - Por ejemplo: firmas digitales e intercambio de llaves
- Algoritmo RSA
- Existen algoritmos derivados de las curvas elipticas

**** Dos llaves
- Se necesitan dos llaves: una publica y otra privada
  - Un mensaje se cifra con la llave publica
  - Ese mensaje solo se puede descifrar con la llave privada
  - La llave publica se comparte y la privada no.

**** RSA
- RSA esta casi obsoleto, debido a multiples vulnerabilidades
- Sirve para ejemplicar el cifrado asimetrico

- Factorización de primos

- Las llaves son basicamente numeros primos muy grandes que se
- Estos numeros son coprimos

- Si solo se tiene uno de los dos

*** Integridad de mensajes, firmas y certificados
- MACS
- Firmas digitales
- Certificados

- "Keyed Hashes"
- Uso de criptografia asimetrica para integridad y autenticidad de mensajes
- Certificados y su diferencia con las llaves

**** Message Authentication Code (MAC)
- Un cifrado puede ser alterado de formas que tenga sentido.
- Un MAC es cualquier codigo o dato transmitido junto con el mensaje que puede ser evaluado para determinar si el mensaje fue alterado.
- Usualmente se utiliza un hash como

***** MAC, HMAC, CBC-MAC
- Un MAC seguro no solo es codigo (hash) tambien debe incluir una llave.
- Una llave MAC no esta relacionada con el cifrado
- Sirve para asegurar que el codigo de autenticacion de mensaje solo puede ser computado por las entidades que conocen la llave.
- No se debe de asumir que el atacante no conoce la funcion de hash, recuerda que una buena seguridad significa...
- MAC protege la integridad del mensaje
- Un atacante sin la llave no debe poder alterar el mensaje sin que se pueda detectar.
- Mientras la llave se mantenga privada, el MAC

****** HMAC
- Hash-based Message Authentication Code
- Es basicamente un hash keyed
- Las funciones de hash son deterministas, dada la misma entrada siempre se produce la misma salida.
- Solo agregar al inicio o al final
- H(K XOR opad, H((K XOR ipad), text))
  - H es la funcion de hash
  - K es la llave que debe de cumplir ciertos requisitos
  - text es cualquier binario que representa el contenido de entrada
  - opad e ipad son dos valoresi
  - B es el tamano del bloque de H (128 bytes)
    1. Si K es mas corto que B, entonces a K se le tienen que agregar ceros de padding hasta ser de longitud B.
    2. Si K es mas largo que B, entonces K se reduce aplicando H a K, osea H(K)
    3. Si se aplico 2 y la llave quedo muy corta, entonces se aplica 1
  - ipad se define com el byte 0x36 repetido B veces
  - opad es el byte 0x5c repetido B veces
  - Los pads parecen arbitrarios pero tienen un sentido de seguridad matematico que ayuda a mitigar
- Primero computas

****** CBC-MAC
- Similar a AES-CBC
- Recordar que CBC es Cipher Block Chaining
- Un MAC a menudo se le llama "tag" (mensaje) del mensaje
- Es info extra que se asocia al principio del contenido
- En notacion matematica un tag se denota a menudo como t
- Asi, un MAC sobre un mensaje m1 produce un tag t1
- El par (m1, t1) es transmitido al receptor para ser verificado

******* MAC Prepend Attack
- Es posible mandar un mensaje manipulado y hacer que parezca que es el mensaje M1 o M2, suponiendo que esten generados por la misma llave.
******** Proceso de ataque, anteponiendo M1 a M2
- Recuperar el primer bloque de M2, denominado M21 (como es AES se toman los primeros 16 bytes)
- Recuperar el resto de bloques de M2, denominado M2r
- Obtener M'2 = t1 XOR M21
- M3 = M1 + M'2 + M2r (+ significa concatenacion)
- Con esto t3 = t2

- Basicamente lo que hace el atacante es reemplazar el primer bloque de M2 por uno manipulado.
- La victima vera todo el mensaje M1 completo (con su padding), un bloque que se vera posiblemente corrupto y el mensaje M2 sin su primer bloque.

**** Firmas digitales
- Protocolo reto-respuesta
  1. El cliente recibe la llave publica del servidor (certificado).
  2. El cliente le manda un reto al servidor.
  3. El cliente le pide al servidor que firme el dato.
  4. El servidor firma el dato y regresa la firma.
  5. El cliente comprueba la firma con la llave publica.

- Quien firma es quien quiere ser autenticado
- Siempre se firma con la llave privada
- Se verifica la firma con la llave publica

- La firma tiene dos propiedades de seguridad
  - Integridad
  - Autenticidad

*** Curvas elipticas
- Alternativa moderna para RSA
- DSA (Digital Signing Algorithm) es un algoritmo asimetrico que solo se usa para firmas digitales.
- Las curvas elipticas se utilizan para firmas digitales y para intercambio de llaves.
- Algoritmo ECDSA
- El parametro es el tipo de curva.

- Entran a sitio web amazon.com
- El sitio des da su llave publica
- Verificar autenticidad del sitio (reto-respuesta)

- Certificados:
  - Metadatos del propietario (subject)
  - Metadatos de la propiedad de confianza (CA/issuer)
  - Llave publica
  - Firma del CA

- El certificado no tiene nada que ver con el cifrado, ni con la protección del canal en general.
- El certificado no se usa directamente para autenticar, eso se hace con firmas digitales.
- El certificado solo es un mecanismo para confiar en la llave publica

- Criptografia asimetrica
  - Firmas digitales
  - Intercambios de llaves

** Combinación de metodos simetricos con asimetricos
- Intercambio de llaves (simetricas)

*** Agree Upon Transmission
- Transporte de llaves RSA
- Sirve para transferir un solo mensaje
- Tienes: llaves_aes, llave_mac, iv
- Llave publica del receptor (viene con el vertificado)
- Cifras las llaves con la llave publica (RSA)
- Firmar llaves planas
- Cifras el mensaje con la llave_aes e IV
- Calcular el HMAC sobre todos los datos
- De sesiones cortas
- Es practico para mensajes largos

- CIfrado en masa: Se cifra una gran cantidad de datos.
- Payload: cargo util

- cliente - servidor
4 llaves de cada lado (sin certificados)
- llave privada ECDH de la parte 1
- llave publica ECDH de la parte 1
- llave privada ECDSA de la parte
- llave publica ECDSA del contrario

- El script termina imprimiendo la llave AES (usen HDFK) acordada en ambos lados

- A veces para establecer un canal de confianza necesitas transmitir datos con poca protección (pueden ser manipulados)
- Eventualmente se llega a tener un canal que se cree protegido (ya se hizo bien el intercambio de llaves)
- Mientras tanto se fueron calculando hashes de todos lo que se transmitio

** AES-GCM
 - IV de tamano de 12 bytes
 - No usar IV 0
 - Segementar lo que transmites
 - Un IV difeente para cada segmento
 - No transmitir mas de 64 gb con la misma llave

** AES-CCM
-

** Transporte de llaves RSA
1. Alguna de las partes genera la llave simetrica. (probablemente el servidor)
2. Se cifra la llave simetrica con una llave publica.
3. La otra parte tiene una llave privada.
4. Se transmite la llave cifrada y se descifra.

- Seguridad hacia delante (Forward Secrecy)

** Transporte de llaves DH
1. Generas

** AEAD
- Authenticated encryption with aditional data
-

** TLS
- Los certificados vienen firmados por un issuer.
- Si quiero comprobar un certificado tambien necesito el certificado del issuer (la llave publica del issuer).
- Se necesita una cadena de certificados, hasta llegar al certificado raiz (autofirmado).
- Si quieres engañar a alguien para entrar a un sitio web falso que necesitas?
  - Sitio web con dominio casi igual.
    - IDS/IPS
    - Educar al usuario

- Envenenamiento de DNS
  - Solo funciona si usas http o si se tiene una llave privada asociada a la cadena de certificados.
    - Se mitiga para http con redireccion hacia https
  - Por que no funciona con https?
    - Por la comprobación de certificados

- Yo tengo un certificado
- Como lo avala un tercero?
- Una cosa es que se compruebe que la entidad es la propietaria verdadera del certificado
- Y otra es que el certificado sea confiable.

*** TLS 1.2
**** Handshake
1. Comienza con un cliente enviando un mensaje hello al servidor. Este mensaje contiene info de configuración, tipo nonce. Tambien esta la lista de Cipher Suites.
   - El objetivo es ponerse de acuerdo en cuanto al algoritmo y protocolos criptograficos a usar. La Cipher Suite da opciones.
   - La seguridad depende del Cipher Suite usado.
2. El servidor recibe un hello cliente, escoge uno de los cipher suites propuestos del cliente. Cuando escoge uno, envia una respuesta con la siguiente info:
   - Hello con nonce
   - Certificado
   - Intercambio de llaves DHE O ECDHE
3. El cliente hace el proceso como auntenticar al servidor, derivar la llave y empezar a enviar datos cifrados.

- TLS solo autentica el servidor, el cliente no envia un certificado para autenticarse.
- Una sesión puede tener varias llaves simetricas.
   - Confidencialidad (transporte en si)
     - Llave emisor-receptor
     - Llave receptor-emisor
   - Autenticación/Integridad (MAC)
     - Llave emisor-receptor
     - Llave receptor-emisor

- Con DH o transporte RSA generas un PMS, que permite generar un master secret.
   - Con el PMS puedes tener un generador de llaves

   - Intercambiar hellos (nonces, certificados, lista de cipher suits)
   - Negociación de cihper suites
   - Autenticacion
   - Intercambio/derivación de llaves
   - ChangeCipherspec
   - Finish (comprobación de hash)
